apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: api
  namespace: iot
  labels:
    app: api
spec:
  serviceName: api-service
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: iot_workshop-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 250m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 500Mi
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-broker-0.kafka-broker.iot.svc.cluster.local:9092,kafka-broker-1.kafka-broker.iot.svc.cluster.local:9092"
