apiVersion: v1
kind: Service
metadata:
  name: spv-installation-service
  namespace: iot
  labels:
    app: spv-installation
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: spv-installation
