apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: smarthome
  namespace: iot
  labels:
    app: smarthome
spec:
  serviceName: smart-home-service
  replicas: 1
  selector:
    matchLabels:
      app: smarthome
  template:
    metadata:
      labels:
        app: smarthome
    spec:
      containers:
      - name: smarthome
        image: local-iot_workshop-smarthome:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 250m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 500Mi
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-broker-0.kafka-broker.iot.svc.cluster.local:9092,kafka-broker-1.kafka-broker.iot.svc.cluster.local:9092"
        - name: REDIS_HOST
          value: "redis-service.iot.svc.cluster.local"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
