apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: iot
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'cars'
        static_configs:
          - targets: ['car-service.iot.svc.cluster.local:8000']
      - job_name: 'spv-installation'
        static_configs:
          - targets: ['spv-installation-service.iot.svc.cluster.local:8000']
      - job_name: 'smart-home'
        static_configs:
          - targets: ['smart-home-service.iot.svc.cluster.local:8000']
