apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: iot
  labels:
    app: prometheus
spec:
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    app: prometheus
