apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-svc
  namespace: iot
  labels:
    app: kafka-ui
spec:
  type: LoadBalancer
  selector:
    app: kafka-ui
  ports:
  - port: 8080
    targetPort: 8080
    name: kafka-ui-port
