apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
  namespace: iot
spec:
  ports:
  - port: 9092
    name: kafka
  - port: 19092
    name: kafka1
  - port: 9093
    name: kafka2
  selector:
    app: kafka-broker
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-headless
  namespace: iot
spec:
  ports:
  - port: 9092
    name: kafka
  selector:
    app: kafka-broker
  clusterIP: None
