apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zoo
  namespace: iot
spec:
  serviceName: zookeeper-headless
  replicas: 2
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:3.3.0
        command:
        - sh
        - -c
        - 'export ZOOKEEPER_SERVER_ID=$(expr $(hostname | grep -o "[[:digit:]]*$") + 1) && export ZOOKEEPER_SERVERS=$(echo $ZOOKEEPER_SERVERS | sed "s/zoo-$(expr $(hostname | grep -o "[[:digit:]]*$")).zookeeper-headless.iot.svc.cluster.local/0.0.0.0/") && /etc/confluent/docker/run'
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        - name: ZOOKEEPER_INIT_LIMIT
          value: "5"
        - name: ZOOKEEPER_SYNC_LIMIT
          value: "2"
        - name: ZOOKEEPER_SERVERS
          value: "zoo-0.zookeeper-headless.iot.svc.cluster.local:2888:3888;zoo-1.zookeeper-headless.iot.svc.cluster.local:2888:3888"
        - name: HOSTNAME
          value: "zoo-0.zookeeper-headless"
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: peer
        - containerPort: 3888
          name: leader-election
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        readinessProbe:
          exec:
            command:
            - bin/sh
            - -c
            - '[ "imok" = "$(echo ruok | nc -w 1 127.0.0.1 2181)" ]'
        volumeMounts:
        - name: data
          mountPath: /var/lib/zookeeper/data
      volumes:
      - name: data
        emptyDir: {}
