{
 "title": "IoT - Cars Tracker",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Cars",
    "query": "Mercedes Benz : car-0, Citroen C3 Aircross : car-1, BMX X3 : car-2"
   }
  ]
 },
 "panels": [
  {
   "title": "$Cars",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 21, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "car_latitude{device=\"$Cars\"}",
     "legendFormat": "latitude"
    },
    {
     "expr": "car_longitude{device=\"$Cars\"}",
     "legendFormat": "longitude"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "car_battery{device=\"$Cars\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "car_speed{device=\"$Cars\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "IoT - Renewable Energy",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Homes",
    "query": "Malaga : spv-installation-0, Barcelona : spv-installation-1, Mallorca : spv-installation-2"
   }
  ]
 },
 "panels": [
  {
   "title": "Energy Distribution",
   "type": "canvas",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "grid{device=\"$Homes\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "home{device=\"$Homes\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "panels{device=\"$Homes\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "battery{device=\"$Homes\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "battery{device=\"$Homes\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "wind_rpm{device=\"$Homes\"}",
     "legendFormat": "wind_rpm"
    }
   ]
  },
  {
   "title": "Home consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "home{device=\"$Homes\"}",
     "legendFormat": "Home"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "battery{device=\"$Homes\"}",
     "legendFormat": "Battery"
    }
   ]
  },
  {
   "title": "Panels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "panels{device=\"$Homes\"}",
     "legendFormat": "Solar Panels"
    }
   ]
  },
  {
   "title": "Grid",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "grid{device=\"$Homes\"}",
     "legendFormat": "Grid"
    }
   ]
  }
 ]
}
{
 "title": "IoT - Smart Home",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "canvas",
   "gridPos": { "h": 17, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "smart_home_temperature{device=\"smarthome-0\", room=\"laundry\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "smart_home_humidity{device=\"smarthome-0\", room=\"laundry\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "smart_home_light{device=\"smarthome-0\", room=\"laundry\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "smart_home_energy{device=\"smarthome-0\", room=\"laundry\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}