apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: iot
  labels:
    app: grafana
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 32000
  selector:
    app: grafana
